package com.group33.cp2.motorph.forms;

import com.group33.cp2.motorph.model.Admin;
import com.group33.cp2.motorph.model.Employee;
import com.group33.cp2.motorph.model.Finance;
import com.group33.cp2.motorph.model.HR;
import com.group33.cp2.motorph.model.IT;
import com.group33.cp2.motorph.dao.EmployeeDetailsReader;
import com.group33.cp2.motorph.service.EmployeeService;
import com.group33.cp2.motorph.util.Constants;
import org.mindrot.jbcrypt.BCrypt;

import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.KeyStroke;

/**
 * Login screen for the MotorPH Payroll System.
 *
 * <p>Authenticates username and password using BCrypt against the
 * {@code src/main/resources/data/Login.csv} file. On success, dispatches
 * to the role-appropriate dashboard:</p>
 * <ul>
 *   <li>HR → {@link HRDashboard}</li>
 *   <li>IT → {@link ITDashboard}</li>
 *   <li>FINANCE → {@link FinanceDashboard}</li>
 *   <li>ADMIN → {@link AdminDashboard}</li>
 *   <li>EMPLOYEE (default) → {@link EmployeeDashboard}</li>
 * </ul>
 *
 * <p>If the login row has {@code changePassword=YES}, the user is prompted to set
 * a new password before proceeding.</p>
 *
 * <p><strong>OOP Pillar — Polymorphism:</strong> The after-login dispatch creates the
 * correct dashboard type based on the role string, demonstrating runtime dispatch
 * through concrete frame types.</p>
 *
 * @author Group13
 * @version 2.1
 */
public class LoginFrame extends javax.swing.JFrame {

    private final EmployeeDetailsReader loginReader = new EmployeeDetailsReader();
    private final EmployeeService       employeeService = new EmployeeService();

    /**
     * Creates the LoginFrame, configures size, close behaviour, and keyboard shortcuts.
     */
    public LoginFrame() {
        initComponents();
        setSize(Constants.FRAME_WIDTH, Constants.FRAME_HEIGHT);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Are you sure you want to exit?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION
                );
                if (response == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        });

        // Allow pressing Enter in either field to trigger login
        txtPassword.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "login");
        txtPassword.getActionMap().put("login", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnLogin.doClick();
            }
        });

        txtUsername.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "login");
        txtUsername.getActionMap().put("login", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnLogin.doClick();
            }
        });

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Password");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel3.setText("MotorPH\u2122");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel4.setText("Payroll System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGap(38, 38, 38))
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLogin)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Reads inputs, authenticates via BCrypt against Login.csv, and dispatches
     * to the appropriate role dashboard.
     */
    private void login() {
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username should not be empty",
                    "Input Error", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password should not be empty",
                    "Input Error", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocus();
            return;
        }

        // Look up Login.csv row: [0]=empNum, [1]=username, [2]=roleName, [3]=password, [4]=changePassword
        String[] loginRow = loginReader.getLoginDataByUsername(username);

        if (loginRow == null) {
            JOptionPane.showMessageDialog(this, "Invalid username or password.",
                    "Login Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String storedHash = loginRow.length > 3 ? loginRow[3].trim() : "";
        if (!BCrypt.checkpw(password, storedHash)) {
            JOptionPane.showMessageDialog(this, "Invalid username or password.",
                    "Login Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if password change is required
        String changePw = loginRow.length > 4 ? loginRow[4].trim() : "NO";
        if ("YES".equalsIgnoreCase(changePw)) {
            handleForcePasswordChange(loginRow[0].trim());
            return;
        }

        // Successful login — dispatch by role
        String empNum = loginRow[0].trim();
        String role   = loginRow.length > 2 ? loginRow[2].trim().toUpperCase() : "EMPLOYEE";

        JOptionPane.showMessageDialog(this, "Login Successful! Welcome, " + username + ".");
        openDashboardForRole(role, empNum);
    }

    /**
     * Prompts the user to set a new password and writes the BCrypt hash to Login.csv.
     * Only proceeds to the dashboard after a successful password change.
     *
     * @param empNum the employee number whose password must be changed
     */
    private void handleForcePasswordChange(String empNum) {
        JPasswordField newPwField     = new JPasswordField();
        JPasswordField confirmPwField = new JPasswordField();
        Object[] message = {
            "Your password must be changed before you can continue.",
            "New Password:", newPwField,
            "Confirm Password:", confirmPwField
        };

        int option = JOptionPane.showConfirmDialog(
                this, message, "Change Password Required", JOptionPane.OK_CANCEL_OPTION);

        if (option != JOptionPane.OK_OPTION) {
            return; // User cancelled — stay on login screen
        }

        String newPw      = new String(newPwField.getPassword()).trim();
        String confirmPw  = new String(confirmPwField.getPassword()).trim();

        if (newPw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "New password cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!newPw.equals(confirmPw)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String hashed = BCrypt.hashpw(newPw, BCrypt.gensalt());
        try {
            boolean updated = loginReader.changeUserPassword(empNum, hashed);
            if (!updated) {
                JOptionPane.showMessageDialog(this, "Password change failed: employee not found.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Password change failed: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Password changed successfully. Please log in again.",
                "Password Changed", JOptionPane.INFORMATION_MESSAGE);
        // Don't dispatch yet — require the user to log in again with the new password
    }

    /**
     * Opens the appropriate dashboard for the given role.
     *
     * @param role   the role string from Login.csv (e.g., "HR", "IT", "FINANCE", "EMPLOYEE")
     * @param empNum the employee number
     */
    private void openDashboardForRole(String role, String empNum) {
        Employee emp = employeeService.getEmployeeById(empNum);

        switch (role) {
            case "HR" -> {
                if (emp instanceof HR hrEmp) {
                    dispose();
                    HRDashboard dash = new HRDashboard(hrEmp, employeeService);
                    dash.setVisible(true);
                } else {
                    // Employee record exists but type is not HR — open fallback
                    NavigationManager.openMenuFrame(this);
                }
            }
            case "IT" -> {
                if (emp instanceof IT itEmp) {
                    dispose();
                    ITDashboard dash = new ITDashboard(itEmp);
                    dash.setVisible(true);
                } else {
                    NavigationManager.openMenuFrame(this);
                }
            }
            case "FINANCE" -> {
                if (emp instanceof Finance finEmp) {
                    dispose();
                    FinanceDashboard dash = new FinanceDashboard(finEmp, employeeService);
                    dash.setVisible(true);
                } else {
                    NavigationManager.openMenuFrame(this);
                }
            }
            case "ADMIN" -> {
                if (emp instanceof Admin adminEmp) {
                    dispose();
                    AdminDashboard dash = new AdminDashboard(adminEmp, employeeService);
                    dash.setVisible(true);
                } else {
                    NavigationManager.openMenuFrame(this);
                }
            }
            default -> {
                // EMPLOYEE and any unrecognised roles
                if (emp != null) {
                    dispose();
                    EmployeeDashboard dash = new EmployeeDashboard(emp);
                    dash.setVisible(true);
                } else {
                    // emp not found in Employee.csv — fall back to legacy menu
                    NavigationManager.openMenuFrame(this);
                }
            }
        }
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // handled via key binding
    }//GEN-LAST:event_txtUsernameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
